### ISSUE TITLE
IE <= 8 support

### ISSUE THREAD

**Issue by XhmikosR** [simonwhitaker/github-fork-ribbon-css#26]
Currently, the ribbon looks pretty bad in IE <= 8. If it's not fixable perhaps support for these browsers should be dropped and show a message or something instead.

**Comment by simonwhitaker** [comment]
What's the best practice on IE support these days? What's the earliest version that it's reasonable to still support?

**Comment by hugorodgerbrown** [comment]
Most annoying answer possible - depends on your target audience.

We have 0.1% users on IE8 (and none lower than that).

**Comment by simonwhitaker** [comment]
Thanks @hugorodgerbrown, always useful to have some numbers. :)

**Comment by XhmikosR** [comment]
GitHub itself supports IE >= 9.

Dropping support for < 9 would mean less code to maintain since the IE css can be removed.

**Comment by XhmikosR** [comment]
Or perhaps we could use fallback images for those browsers?

**Comment by hugovk** [comment]
Since 12th January 2016, Microsoft only supports IE <=8 for a few Windows Embedded operating systems. 

For desktop only IE11 is supported (apart form IE9 on Vista), and IE9, 10 and 11 are supported for different server operating systems.

https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
https://support.microsoft.com/en-us/lifecycle#gp/Microsoft-Internet-Explorer

**Comment by simonwhitaker** [comment]
I'm going to close this one out, like the lazy, arrogant Mac user I am. 😁 Feel free to send a pull request if you have a suggested fix you'd like to see included.
