### ISSUE TITLE
How about using with npm?

### ISSUE THREAD

**Issue by plantain-00** [simonwhitaker/github-fork-ribbon-css#52]

**Comment by swervo** [comment]
I've taken the liberty of publishing this to npm. I didn't need to make any changes. Just forked it and published it. So:

`npm i --save github-fork-ribbon-css`

Should do it for you. I've recently switched to webpack so to be able to drop bower is helpful.

@simonwhitaker I'm happy to take this down if you want to publish it yourself - I only did it because I wanted to use it with npm

**Comment by plantain-00** [comment]
@swervo thanks
