### ISSUE TITLE
use anchor text as text inside ribbon and display regular tooltip as the title text on hover

### ISSUE THREAD

**Issue by Inna-r** [simonwhitaker/github-fork-ribbon-css#53]

**Comment by simonwhitaker** [comment]
I'm not quite sure I understand what you're asking for here – I suspect I'm just being a bit slow! Could you explain please? (Or even better, submit a pull request!)

**Comment by englishextra** [comment]
@simonwhitaker Perhaps I can explain, since title attr is used for text, it ruined my external links managing.

All my external links get some title text saying that example.com will open in a new tab. So the ribbon anchor gets this text. ```data-attribute``` will be fine and can be accessed via css.

BTW It's not about submitting a PR, it's a logic which is up to author to change.

So:

```css
.github-fork-ribbon:after {
	/* Set the text from the data-ribbon attribute */
	content: attr(data-ribbon);
```

```html
<a class="github-fork-ribbon"
 href="https://github.com/englishextra/englishextra.github.io"
 title="Fork me on GitHub"
 data-ribbon="Fork me on GitHub">Fork me on GitHub</a>
```

I sent the PR https://github.com/simonwhitaker/github-fork-ribbon-css/pull/58

**Comment by hugovk** [comment]
PR #58 has been merged, closing this.
